spring:
  application:
    name: sms-service
  profiles:
    include: 'kafka'
    active: 'local'
  cloud:
    loadbalancer:
      ribbon:
        enable: false

server:
  port: 9020


---
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  config:
    activate:
      on-profile: k8s
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

